# Generated by Django 5.2.8 on 2025-11-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('condicion', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
