# Generated by Django 5.2.8 on 2025-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='departamento',
            field=models.CharField(choices=[('Fiscalización', 'Fiscalización'), ('Recaudación', 'Recaudación'), ('Inmuebles Urbanos', 'Inmuebles Urbanos'), ('Gerencia de Licores', 'Gerencia de Licores'), ('Gerencia General', 'Gerencia General'), ('Jurídica', 'Jurídica'), ('Administración y Finanzas', 'Administración y Finanzas')], max_length=50),
        ),
    ]
