# Generated by Django 5.2.8 on 2025-11-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_activo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='condicion',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('dañado', 'Dañado')], default='operativo', max_length=20),
        ),
    ]
