# Generated by Django 5.2.8 on 2025-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_activo_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='categoria_principal',
            field=models.CharField(choices=[('', 'Seleccione una categoría'), ('equipo_informatico', 'Equipo Informático'), ('mueble', 'Mueble'), ('equipo_especializado', 'Equipo Especializado'), ('otro', 'Otro')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('pc_escritorio', 'PC de Escritorio'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('servidor', 'Servidor'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('escritorio', 'Escritorio'), ('silla', 'Silla'), ('archivador', 'Archivador'), ('estanteria', 'Estantería'), ('mesa', 'Mesa'), ('scanner', 'Scanner'), ('proyector', 'Proyector'), ('telefono', 'Teléfono IP'), ('switch', 'Switch de Red'), ('router', 'Router'), ('otro_equipo', 'Otro Equipo'), ('herramienta', 'Herramienta'), ('material', 'Material de Oficina')], max_length=50),
        ),
    ]
