# Generated by Django 5.2.7 on 2025-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activo_categoria_principal_activo_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('equipos informáticos', 'Equipos Informáticos'), ('pc_escritorio', 'PC de Escritorio'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('servidor', 'Servidor'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('mueble', 'Mueble'), ('escritorio', 'Escritorio'), ('silla', 'Silla'), ('archivador', 'Archivador'), ('estanteria', 'Estantería'), ('mesa', 'Mesa'), ('equipos especializados', 'Equipos Especializados'), ('scanner', 'Scanner'), ('proyector', 'Proyector'), ('telefono', 'Teléfono IP'), ('switch', 'Switch de Red'), ('router', 'Router'), ('otro equipo', 'Otro Equipo'), ('herramienta', 'Herramienta'), ('material', 'Material de Oficina')], max_length=50),
        ),
    ]
